server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ljymysqlpwd
  redis:
    host: localhost
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
pagehelper:
  reasonable: true

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8081/xxl-job-admin  #xxl-job调度中心地址
    executor:
      ip: 127.0.0.1 #注册到调度中心的执行器ip地址
      port: 9510
      appname: cfjg-job #执行器的名称
